import unittest
import ManipulateData.Reader as Reader
import pprint


class HTMLReaderTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self.file_name: str = "test"
        self.expected: str = """<!DOCTYPE html>
<html>
<head>
    <title>Test</title>
</head>
<body>
<h1>Test</h1>
<p>Test</p>
</body>
</html>"""

    def tearDown(self) -> None:
        self.file_name = None

    def test_HTMLReader(self) -> None:
        reader: Reader.AbstractReader = Reader.HTMLReader(self.file_name)
        result: str = reader.get_data()
        self.assertEqual(self.expected, result)


class CSVReaderTestCase(unittest.TestCase):
    def setUp(self) -> None:
        self.file_name: str = "test_timetable"
        self.expected: list[list[str]] = [['Sem',
                                           'Class Code',
                                           'Learning Module',
                                           'Instructor',
                                           'Venue',
                                           'Period',
                                           'Time',
                                           'Sun',
                                           'Mon',
                                           'Tue',
                                           'Wed',
                                           'Thu',
                                           'Fri',
                                           'Sat'],
                                          ['2',
                                           'COMP221-221',
                                           'OBJECT ORIENTED TECHNOLOGIES',
                                           'WONG UN HONG',
                                           'N_54',
                                           '2023/01/05-2023/04/22',
                                           '10:00-11:30',
                                           '0',
                                           '0',
                                           '1',
                                           '0',
                                           '0',
                                           '0',
                                           '0'],
                                          ['null',
                                           'null',
                                           'null',
                                           'WONG UN HONG',
                                           'N_54',
                                           '2023/01/05-2023/04/22',
                                           '11:30-13:00',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '1',
                                           '0',
                                           '0'],
                                          ['2',
                                           'COMP222-221',
                                           'INTERNET PROGRAMMING I',
                                           'CALANA CHAN MEI POU',
                                           'N_54',
                                           '2023/01/05-2023/04/22',
                                           '10:00-11:30',
                                           '0',
                                           '1',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '0'],
                                          ['null',
                                           'null',
                                           'null',
                                           'CALANA CHAN MEI POU',
                                           'N_54',
                                           '2023/01/05-2023/04/22',
                                           '11:30-13:00',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '1',
                                           '0'],
                                          ['2',
                                           'COMP223-221',
                                           'SOFTWARE ENGINEERING',
                                           'AMANG KIM SONGKYOO',
                                           'N_56',
                                           '2023/01/05-2023/04/22',
                                           '11:30-13:00',
                                           '0',
                                           '1',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '0'],
                                          ['null',
                                           'null',
                                           'null',
                                           'AMANG KIM SONGKYOO',
                                           'N_56',
                                           '2023/01/05-2023/04/22',
                                           '10:00-11:30',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '1',
                                           '0'],
                                          ['2',
                                           'COMP224-221',
                                           'DATABASE MANAGEMENT SYSTEMS',
                                           'YANG XU',
                                           'A214',
                                           '2023/01/05-2023/04/22',
                                           '11:30-13:00',
                                           '0',
                                           '0',
                                           '1',
                                           '0',
                                           '0',
                                           '0',
                                           '0'],
                                          ['null',
                                           'null',
                                           'null',
                                           'YANG XU',
                                           'A211',
                                           '2023/01/05-2023/04/22',
                                           '10:00-11:30',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '1',
                                           '0',
                                           '0'],
                                          ['2',
                                           'COMP225-221',
                                           'NETWORK AND SYSTEM ADMINISTRATION',
                                           'LIAM LEI KIN',
                                           'N_54',
                                           '2023/01/05-2023/04/22',
                                           '14:30-17:30',
                                           '0',
                                           '1',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '0'],
                                          ['2',
                                           'MENG221-221',
                                           'ENGLISH IV',
                                           'CHUI SAI CHAK',
                                           'N_52',
                                           '2023/01/05-2023/04/22',
                                           '14:30-17:30',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '0',
                                           '1',
                                           '0'],
                                          ['null',
                                           'null',
                                           'null',
                                           'HO SIO WA',
                                           'B304',
                                           '2023/02/13-2023/03/18',
                                           '14:30-17:30',
                                           '0',
                                           '0',
                                           '1',
                                           '0',
                                           '0',
                                           '0',
                                           '0']]

    def tearDown(self) -> None:
        self.file_name = None

    def test_CSVReader(self) -> None:
        reader: Reader.AbstractReader = Reader.CSVReader(self.file_name)
        result: list[list[str]] = reader.get_data()
        self.assertEqual(self.expected, result)
